name: Zip & Upload to S3 Bucket

on:
  push:
    tags:
      - "*"

jobs:
  zip-and-upload:
    name: "Zip and Upload to S3 Bucket"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install zip utility
        run: sudo apt-get install -y zip

      - name: Zip repository
        run: zip -r ggen-template@${{ github.ref_name }}.zip .

      - name: Show zipped file
        run: ls -lh
