name: Zip & Upload to S3 Bucket

on:
  push:
    tags:
      - "*"

jobs:
  zip-and-upload:
    name: "Zip and Upload to S3 Bucket"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install zip utility
        run: sudo apt-get install -y zip

      - name: Zip repository
        run: zip -r ggen-template@${{ github.ref_name }}.zip .

      - name: Show zip file size
        run: |
          FILE="ggen-template@${{ env.ref_name }}.zip"
          if [ -f "$FILE" ]; then
            SIZE=$(stat -c%s "$FILE")
            echo "Filename: $FILE"
            echo "Size: $SIZE bytes"
          else
            echo "File $FILE does not exist"
          fi
