name: Zip & Upload to S3 Bucket

on:
  push:
    tags:
      - "*"

jobs:
  zip-and-upload:
    name: "Zip and Upload to S3 Bucket"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install zip utility
        run: sudo apt-get install -y zip

      - name: Zip repository
        run: zip -r ggen-template@${{ github.ref_name }}.zip .

      - name: Check file size
        run: du -sh ggen-template@${{ github.ref_name }}.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Upload to S3
        run: aws s3 cp ggen-template@${{ github.ref_name }}.zip s3://${{ secrets.AWS_BUCKET }}/ggen-template@${{ github.ref_name }}.zip
